---
title: "3_sensitivity and interpretations"
author: "Joy_Fu"
date: "2023-04-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list = ls())
pacman::p_load(tidyverse, gtsummary, epiflow, PheWAS, UpSetR)
raw_data_path = "/Users/Mingzhou/Desktop/Projects/AD-LOE-genetics/data/"
output_path = "/Users/Mingzhou/Desktop/Projects/AD-LOE-genetics/output/"
# Source in useful functions
source("functions.R")
```

# Part 1. Phecodes & ICD-10
## 1. Epilepsy
```{r}
epi_phecode = c("345", "345.1", "345.11", "345.12", "345.3")
icd_short = icd.data::icd10cm2016 %>% as.data.frame() %>% 
  mutate(code = as.character(code)) %>% 
  select(code, long_desc) %>% dplyr::rename("code_nodigit" = "code")
epi_tbl = PheWAS::phecode_map %>% 
  filter(vocabulary_id == "ICD10CM" & phecode %in% epi_phecode) %>% 
  mutate(code_nodigit = str_replace(code, "\\.", "")) %>% 
  left_join(icd_short, by = "code_nodigit") %>% 
  select(phecode, code, long_desc) %>% unique() %>% drop_na() %>% 
  mutate(long_desc = gsub("<0xa0>", " ", long_desc))
write_delim(epi_tbl, delim = "\t", 
            file = paste0(output_path, "epi_phecode_tbl.txt"), quote = "none")
```

## 2. AD
```{r}
ad_tbl = PheWAS::phecode_map %>% 
  filter(vocabulary_id == "ICD10CM" & phecode == "290.11") %>% 
  mutate(code_nodigit = str_replace(code, "\\.", "")) %>% 
  left_join(icd_short, by = "code_nodigit") %>% 
  select(phecode, code, long_desc) %>% unique() %>% drop_na() %>% 
  mutate(long_desc = gsub("<0xa0>", " ", long_desc))
write_delim(ad_tbl, delim = "\t", 
            file = paste0(output_path, "ad_phecode_tbl.txt"), quote = "none")
```

# Part 2. Shared genes
```{r}
load(file = paste0(raw_data_path, "modeling/EUR/snps_interpret/rsID_check_AD.rda"))
load(file = paste0(raw_data_path, "modeling/EUR/snps_interpret/rsID_check_epi.rda"))
loe_df = cbind(loe_set, rep(1, length(loe_set))) %>% as.data.frame()
names(loe_df) = c("gene", "LOE_specific")
ad_df = cbind(ad_set, rep(1, length(ad_set))) %>% as.data.frame()
names(ad_df) = c("gene", "AD_specific")
shared_df = cbind(shared_set, rep(1, length(shared_set))) %>% as.data.frame()
names(shared_df) = c("gene", "Shared")

genes_df = shared_df %>% full_join(ad_df) %>% full_join(loe_df) %>% 
  mutate(Shared = as.numeric(Shared),
         AD_specific = as.numeric(AD_specific),
         LOE_specific = as.numeric(LOE_specific))
# Replace NAs with 0
genes_df[is.na(genes_df)] = 0
```

```{r}
pdf(paste0(output_path, "upset_shared.pdf"), width = 8, height = 5)
upset(genes_df, sets = c("Shared", "AD_specific", "LOE_specific"), 
      sets.bar.color = "#56B4E9",
      order.by = "freq", empty.intersections = "on")
dev.off()
```


# Part 3. High vs. Low pred scores
```{r}
load(file = paste0(raw_data_path, "modeling/EUR/explore_df_final.rda"))
```

## 1. Top 20% vs. bottom 20% score
```{r}
explore_df_short = explore_df_final %>% 
  filter(high_pred_score == 1 | low_pred_score == 1)
explore_df_short %>% 
  mutate(n_conditions = epilepsy + AD) %>% 
  dplyr::select(high_pred_score, age_last_visit, female, record_length, enc_per_yr, 
         epilepsy, e4count, dementia, htn, diabetes, hyperlipid, AD, 
         epi_age_diagnosis, dem_age_diagnosis, ad_age_diagnosis, n_conditions,
         condition, AD_PRS_full_norm, AD_PRS_rmapoe_norm) %>% 
  tbl_summary(by = high_pred_score) %>% add_p()
```

## 2. Number of conditions
```{r}
explore_df_final %>% 
  mutate(high_sharedRS.cat = as.factor(high_sharedRS),
         female.cat = as.factor(female)) %>%
  dplyr::select(high_sharedRS.cat, age_last_visit, female.cat, record_length, 
         enc_per_yr, epilepsy, e4count, dementia, htn, diabetes, stroke, 
         hyperlipid, ad, epi_age_diagnosis, dem_age_diagnosis, ad_age_diagnosis, 
         condition, shared_RS) %>% 
  tbl_summary(by = condition) %>% add_p()
```

## 3. Forest plot
```{r}
var_names = c('epilepsy', 'AD', 'dementia', # 3
              'age_last_visit', 'female', 'record_length', 'enc_per_yr', # 4
              'htn', 'diabetes', 'hyperlipid', # 3
              'e4count', 'AD_PRS_full_norm', 'AD_PRS_rmapoe_norm') # 3
explanary_names = c('Late-onset Epilepsy', "Alzheimer's Disease", 'Dementia', 
                    'Age at last visit', 'Sex (female)', 'EHR record length', 
                    'EHR record density', 'Hypertension', 'Diabetes', 'Hyperlipid', 
                    'APOE-e4 allele count', 'AD PRS full', 'AD PRS w/o APOE')

model_lst = list()
for (i in 1:length(var_names)) {
  model_lst[[i]] = lm(as.formula(paste0('pred_score ~ ', var_names[i], 
                                        " + PC1 + PC2 + PC3 + PC4")),
                      data = explore_df_short)
}
table1 = build_coef_table(var_names, model_lst)

forest.data = table1 %>% 
  dplyr::select(beta, lower_CI, upper_CI) %>% 
  mutate(sub = c('Primary outcomes', rep(NA, 2), 
                 'Demographics', rep(NA, 3), 
                 'Health conditions' , rep(NA, 2),
                 'AD genetics', rep(NA, 2))) %>% 
  mutate(beta = round(as.numeric(as.character(beta)), 3),
         lower_CI = round(as.numeric(as.character(lower_CI)), 3),
         upper_CI = round(as.numeric(as.character(upper_CI)), 3)) %>% 
  mutate(class = c(rep(2, 3), rep(3, 4), rep(4, 3), rep(5, 3)))

tabletext = cbind(
  c("Category", "\n", forest.data$sub),
  c("Exposure", "\n", explanary_names),
  c("Beta coefficient (95% CI)", "\n", as.character(table1$text))
)
pop.cols = c("black","black","black", "black", "black")
```

```{r}
pdf(paste0(output_path, "Shared_RS_Forest.pdf"), width = 10, height = 5)
forestplot(labeltext = tabletext, graph.pos = 1,
           mean = c(NA, NA, forest.data$beta), 
           lower = c(NA, NA, forest.data$lower_CI),
           upper = c(NA, NA, forest.data$upper_CI),
           xticks = c(-0.05, 0, 0.05, 0.1, 0.15, 0.2, 0.25),
           zero = 0,
           title = "Figure 4. Associations between covariates and shared genetic risk score (n = 18,742)",
           xlab = "Effect Size",
           txt_gp = fpTxtGp(label = list(gpar(fontface = "bold", cex = 0.8, 
                                              fontfamily = "serif"),
                                         gpar(cex = 0.8, fontfamily = "serif"),
                                         gpar(cex = 0.8, fontfamily = "serif")),
                            ticks = gpar(cex = 0.6, fontfamily = "serif"),
                            xlab = gpar(cex = 0.7, fontfamily = "serif"),
                            title = gpar(cex = 1, fontfamily = "serif")),
           col = fpColors(text = pop.cols[c(1, 1, forest.data$class)], 
                          box  ="black",
                          lines = "black", 
                          zero ="gray50"),
           cex = 0.2, lineheight = "auto", boxsize = 0.25, 
           lwd.ci = 1, ci.vertices = TRUE, ci.vertices.height = 0.15)
dev.off()
```

# Part 4. ATLAS vs. AOU
```{r}
load(file = paste0(raw_data_path, "AOU/patient_final_AOU.rda"))
load(file = paste0(raw_data_path, "modeling/EUR/patient_final_EUR.rda"))

atlas_sample = patient_final_EUR %>% 
  mutate(htn = if_else(!is.na(HTNDate), 1, 0),
         diabetes = if_else(!is.na(DiabetesDate), 1, 0),
         hyperlipid = if_else(!is.na(HyperlipidDate), 1, 0),
         sample = "ATLAS") %>% 
  mutate(either = case_when(
    AD == 0 & epilepsy == 0 ~ 0,
    TRUE ~ 1
  )) %>% 
  filter(!is.na(either)) %>% filter(!is.na(AD) | !is.na(epilepsy)) %>% 
  select(AD, epilepsy, age_last_visit, female, record_length, enc_per_yr, 
         htn, diabetes, hyperlipid, sample) 
dim(atlas_sample) # dim = (17031,10)

aou_sample = patient_final_AOU %>% 
  mutate(sample = "AOU") %>% 
  select(AD, epilepsy, age_last_visit, female, record_length, enc_per_yr, 
         htn, diabetes, hyperlipid, sample) 
dim(aou_sample) # dim = (43351,10)
```

```{r}
full_compare = rbind(atlas_sample, aou_sample) %>% as.data.frame()
full_compare %>% 
  tbl_summary(by = sample) %>% add_p()
```


# Part 5. Causal inference
```{r}
library(CMAverse)
load("~/Desktop/Projects/AD-LOE-genetics/data/modeling/EUR/explore_df_final.rda")
```

## 1. Data preprocessing
```{r}
# split prediction scores into quintiles
explore_df_final = explore_df_final %>%
  mutate(quintile = ntile(pred_score, 5)) %>%
  relocate(quintile, .after = low_pred_score)

table(explore_df_final$epilepsy)
table(explore_df_final$AD)

# remove missing info.
# remove epilepsy patients with a recorded age at the time of AD diagnosis higher than that at the time of epilepsy diagnosis
epi_med = explore_df_final %>%
  drop_na(epilepsy, AD, age_last_visit, female, record_length, enc_per_yr, PC1, PC2, PC3, PC4, e4count) %>%
  filter(if_else(epilepsy==1 & !is.na(ad_age_diagnosis), epi_age_diagnosis < ad_age_diagnosis, TRUE))

table(epi_med$epilepsy)
table(epi_med$AD)

# add levels
epi_med$e4count = factor(epi_med$e4count)
epi_med$quintile = factor(epi_med$quintile, levels = c(1:5))
```

## 2. Assumption check
```{r}
### make sure mediation assumptions are met ###
# assumption 1: prediction score (exposure) is significantly associated with AD status (outcome)
model.0 = glm(AD ~ quintile + age_last_visit + female + record_length + enc_per_yr + PC1 + PC2 + PC3 + PC4 +
                htn + diabetes + hyperlipid,
              data = epi_med,
              family ='binomial')

summary(model.0)

# assumption 2: prediction score is significantly associated with epilepsy status (mediator), 
model.M = glm(epilepsy ~ quintile + age_last_visit + female + record_length + enc_per_yr + PC1 + PC2 + PC3 + PC4 +
                htn + diabetes + hyperlipid,
              data = epi_med,
              family ='binomial')

summary(model.M)

# assumption 3: epilepsy status is significantly associated with AD status when regressing the latter on the former and prediction score
# assumption 4: prediction score is less significantly associated in (3) than (1)
model.Y = glm(AD ~ quintile + epilepsy + age_last_visit + female + record_length + enc_per_yr + PC1 + PC2 + PC3 + PC4 +
                htn + diabetes + hyperlipid,
              data = epi_med,
              family ='binomial')

summary(model.Y)

# assumption 4: epilepsy and prediction score does not interact
model.I = glm(AD ~ quintile * epilepsy + age_last_visit + female + record_length + enc_per_yr + PC1 + PC2 + PC3 + PC4 +
                htn + diabetes + hyperlipid,
              data = epi_med,
              family ='binomial')
summary(model.I)
```

```{r}
# caclulate ORs and CIs
# ORs
model0_quint5_or = exp(model.0[[1]][5])
modelM_quint5_or = exp(model.M[[1]][5])
modelY_quint5_or = exp(model.Y[[1]][5])
modelI_quint5_or = exp(model.I[[1]][5])
modelY_epi_or = exp(model.Y[[1]][6])
modelI_epi_or = exp(model.I[[1]][6])
# CIs
model0_ci = confint(model.0)
modelM_ci = confint(model.M)
modelY_ci = confint(model.Y)
modelI_ci = confint(model.I)
model0_lower_quint5 = exp(model0_ci[5,1])
model0_upper_quint5 = epx(model0_ci[5,2])
modelM_lower_quint5 = exp(modelM_ci[5,1])
modelM_upper_quint5 = exp(modelM_ci[5,2])
modelY_lower_quint5 = exp(modelY_ci[5,1])
modelY_upper_quint5 = exp(modelY_ci[5,2])
modelI_lower_quint5 = exp(modelI_ci[5,1])
modelI_upper_quint5 = exp(modelI_ci[5,2])
modelY_lower_epi = exp(modelY_ci[6,1])
modelY_upper_epi = exp(modelY_ci[6,2])
modelI_lower_epi = exp(modelI_ci[6,1])
modelI_upper_epi = exp(modelI_ci[6,2])
```

## 3. Mediation
```{r}
cma_res <- cmest(data = epi_med, model = 'rb', outcome = 'AD', exposure = 'quintile',
                 mediator = 'epilepsy', 
                 basec = c('age_last_visit', 'female', 'record_length', 'enc_per_yr', 'PC1',
                           'PC2', 'PC3', 'PC4', 'htn', 'diabetes', 'hyperlipid'),
                 EMint = FALSE, mreg = list('logistic'), yreg = 'logistic',
                 astar = 1, a = 5, mval = list(1), estimation = 'imputation', inference = 'bootstrap',
                 nboot = 1000, boot.ci.type = 'per')

summary(cma_res)
```

